### ISSUE TITLE
爬山法是不是应该无解才对？

### ISSUE THREAD

**Issue by Akiract** [q13926117923/zuoye#1]

**Comment by q13926117923** [comment]
你也有这个题目吧，我就不介绍了。
我的算法是这样的：
每走一层，把所有比本节点剩余预估值低的相邻节点都保留在一个优先队列里（爬山规则，保证单调），把相邻节点预估值比本节点高的抛弃掉，每次递归执行，采用深度优先的方法把所有合理的路线遍历，遍历到叶子节点或者没有符合爬山规则相邻节点将会返回上一层，遍历其他保留下来的节点，由于本题正确的路线的节点预估值也是单调的，所以有解。

**Comment by q13926117923** [comment]
补充一下。。。书上说的爬山法好像是不保存别的节点。。我要改一下，你是对的

**Comment by Akiract** [comment]
thanx so much
